### PR TITLE
use predefined icons for badges (backwards compat)

### LINKED ISSUE #9065: Basic code intel info button is wrong size and color
cc @efritz

### PR DESCRIPTION
**Pull request by twop**
this should fix https://github.com/sourcegraph/sourcegraph/issues/9065
leveraging new api done here: https://github.com/sourcegraph/sourcegraph/pull/10517

### CODE REVIEW

File: shared/badges.ts [hunk 1]
```diff
@@ -62,6 +62,7 @@ function makeInfoIcon(color: string): string {
  * The badge to send back on all results that come from searched-based data.
  */
 export const impreciseBadge: sourcegraph.BadgeAttachmentRenderOptions = {
+    kind:'info',
```
Comment (efritz) [inline shared/badges.ts:65]:
```suggestion
    kind: 'info',
```

**Comment by efritz** [comment]
Build is currently failing (I think some other repo needs to have a version bumped too).

https://buildkite.com/sourcegraph/code-intel-extensions/builds/3119

**Comment by twop** [comment]
@efritz I like the latency here. 20 sec after I published this PR you already posted a comment 👍
